export const TEMPLATE = [
    {
        type: "input",
        name: "name",
        label: "Name",
        valueType: "string",
        defaultValue: [""],
        placeholder: "Input name here",
        required: true,
    },
    {
        type: "input",
        name: "age",
        label: "Age",
        valueType: "number",
        defaultValue: ["18"],
        placeholder: "Input age here",
    },
    {
        type: "textarea",
        name: "memo",
        label: "Memo",
        valueType: "string",
        defaultValue: ["default memo"],
        placeholder: "Input memo here",
        required: true,
    },
    {
        type: "choice",
        name: "options",
        label: "Options",
        valueType: "number",
        multi: true,
        defaultValue: [1],
        placeholder: "Select options",
        required: true,
    },
    {
        type: "choice",
        name: "option",
        label: "Single Option",
        valueType: "number",
        defaultValue: [1],
        placeholder: "Select option",
    },
    {
        type: 'file',
        name: 'logo',
        label: 'LOGO',
        defaultValue: [],
    },
    {
        type: 'file',
        name: 'images',
        label: 'Images',
        defaultValue: [],
        multi: true,
    },
];